version: '0.1'
services:
    php-apache:
        container_name: php-apache
        build:
            context: .
            dockerfile: dockerfile
        depends_on:
            - db
        ports:
            - 8080:80
    db:
        container_name: db
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "8081:3306"
